---
title: "Untitled"
output: html_document
date: '2023-01-09'
---

```{r setup, include=FALSE}
##################################################################################################
# SETUP
##################################################################################################

# Clear workspace of all objects and unload all extra (non-base) packages
rm(list = ls(all = TRUE))
if (!is.null(sessionInfo()$otherPkgs)) {
  res <- suppressWarnings(
    lapply(paste('package:', names(sessionInfo()$otherPkgs), sep=""),
           detach, character.only=TRUE, unload=TRUE, force=TRUE))
}

pacman::p_load(tidyverse#,
               #parallel, #mclapply; detectCores()
               #sf,  
               #units # set_units()
)    

set.seed(1)

source("file_paths.R")
source("functions.R")
var_names <- read_rds(file.path("Output", "keep_vars.rda"))

```

```{r}
##################################################################################################
# LOAD DATA
##################################################################################################

model_eval0 <- readRDS(file.path("Output", "model_eval.rda")) %>%
  filter(reference == "gs_estimate") %>%
  mutate(
    variable = factor(variable, levels = var_names)
  )


selected_campaigns <- read_rds(file.path("Output", "selected_campaigns.rda"))

```


# Campaigns


```{r}
# --> error 
selected_campaigns %>% 
  group_by(design, version, variable) %>% 
  summarize(
    campaigns = length(unique(campaign)),
    locations = length(unique(location))
    )

```



# Model Performances

```{r}
model_eval0 %>%
  group_by(variable, out_of_sample, design, version) %>%
  summarize(
    n = n(),
    mean_r2 = mean(MSE_based_R2),
    rmse = mean(RMSE)
  )

model_eval0 %>%
  filter(out_of_sample == "CV") %>%
  ggplot(aes(x=variable, y=MSE_based_R2, fill=version)) + 
  #facet_wrap(~design) + 
  geom_boxplot()
  
```



# Compare Predictions -  Scatterplots/correlations

```{r}


```


